import Web3 from 'web3';

const web3=new Web3(new Web3.providers.HttpProvider("http://localhost:7545"));
let vizagBlocksABI=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"placeToOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"placeCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"ownerPlaceCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"places","outputs":[{"name":"id","type":"uint256"},{"name":"name","type":"string"},{"name":"publicId","type":"string"},{"name":"dbRecordId","type":"string"},{"name":"totalVotes","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"placeId","type":"uint256"},{"indexed":false,"name":"name","type":"string"},{"indexed":false,"name":"publicId","type":"string"},{"indexed":false,"name":"dbRecordId","type":"string"},{"indexed":false,"name":"placeCount","type":"uint256"}],"name":"NewPlace","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"placeId","type":"uint256"},{"indexed":false,"name":"totalVotes","type":"uint256"}],"name":"NewVote","type":"event"},{"constant":false,"inputs":[{"name":"_name","type":"string"},{"name":"_publicId","type":"string"},{"name":"_dbRecordId","type":"string"}],"name":"addPlace","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_placeId","type":"uint256"}],"name":"getPlace","outputs":[{"name":"","type":"uint256"},{"name":"","type":"string"},{"name":"","type":"string"},{"name":"","type":"string"},{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_placeId","type":"uint256"}],"name":"vote","outputs":[{"name":"","type":"bool"}],"payable":true,"stateMutability":"payable","type":"function"}]
let vizagBlocksAddress='0xc2dc9281e3219f04e76f4aba8faa879ad4839994';
web3.eth.defaultAccount = web3.eth.accounts[0]

const vizagBlocksContract=web3.eth.contract(vizagBlocksABI).at(vizagBlocksAddress);
export default vizagBlocksContract;
